import { useEffect, useState, type ReactNode } from 'react';
import { Link } from 'wouter';
import axios from 'axios';
import { Logo } from '../lib/ui';
import { defaultCitizenProfile, type CitizenProfile, type Recommendation } from '../lib/citizen';
import { useLanguage, format } from '../lib/i18n';
import { LanguageSwitcher } from './LanguageSwitcher';
import { ThemeToggle } from './ThemeToggle';

export function CitizenHeader() {
  const { t } = useLanguage(); return <header className="flex items-center justify-between border-b border-border px-6 py-5 md:px-12"><Link href="/citizen"><Logo /><span className="sr-only">{t('citizen.home')}</span></Link><div className="flex items-center gap-1 md:gap-3"><Link href="/citizen/profile/view" className="hidden rounded-full px-3 py-2 font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground transition hover:bg-secondary sm:block">{t('nav.yourProfile')}</Link><Link href="/citizen/saved" className="hidden rounded-full px-3 py-2 font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground transition hover:bg-secondary sm:block">{t('nav.savedSchemes')}</Link><LanguageSwitcher /><ThemeToggle /><Link href="/admin-login" className="rounded-full border border-border px-3 py-2 font-mono text-[10px] uppercase tracking-[0.14em] transition hover:bg-foreground hover:text-background">{t('nav.administrator')} ↗</Link></div></header>;
}
export function CitizenShell({ children }: { children: ReactNode }) {
  const { t } = useLanguage();
  return <div className="min-h-screen bg-background text-foreground"><CitizenHeader /><main>{children}</main><footer className="mt-20 border-t border-border px-6 py-8 md:px-12"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-3 text-xs text-muted-foreground md:flex-row"><span>{t('citizen.footerMain')}</span><span>{t('citizen.footerSub')}</span></div></footer></div>;
}
export function cleanStoredProfile(data: Partial<CitizenProfile>): Partial<CitizenProfile> { const clean: Partial<CitizenProfile> = {}; for (const [key, value] of Object.entries(data)) { if (typeof value === 'string' && value.trim().length > 0) clean[key as keyof CitizenProfile] = value; } return clean; }
export function loadCitizenProfile(): CitizenProfile { try { const saved = window.localStorage.getItem('sahayak-citizen-profile'); return saved ? { ...defaultCitizenProfile, ...cleanStoredProfile(JSON.parse(saved)) } : defaultCitizenProfile; } catch { return defaultCitizenProfile; } }
export function saveCitizenProfile(profile: CitizenProfile) { window.localStorage.setItem('sahayak-citizen-profile', JSON.stringify(cleanStoredProfile(profile))); }
export async function fetchCitizenProfile(): Promise<CitizenProfile> { try { const res = await axios.get<Partial<CitizenProfile>>('/api/citizen/profile'); return { ...defaultCitizenProfile, ...cleanStoredProfile(res.data) }; } catch { return defaultCitizenProfile; } }
export async function saveCitizenProfileToApi(profile: CitizenProfile): Promise<void> { await axios.post('/api/citizen/profile', profile); }
export function useCitizenProfile() { const [profile, setProfile] = useState<CitizenProfile>(defaultCitizenProfile); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const save = async () => { setSaving(true); try { await saveCitizenProfileToApi(profile); } finally { setSaving(false); } }; useEffect(() => { let cancelled = false; fetchCitizenProfile().then(p => { if (!cancelled) setProfile(p); if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []); return { profile, setProfile, loading, saving, save }; }
export function useCitizenRecommendations(profile: CitizenProfile, ready: boolean) { const [recommendations, setRecommendations] = useState<Recommendation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [reloadKey, setReloadKey] = useState(0); const reload = () => setReloadKey((n) => n + 1); useEffect(() => { if (!ready) return; let cancelled = false; setLoading(true); setError(null); axios.post<Recommendation[]>('/api/citizen/recommendations', profile).then(response => { if (!cancelled) setRecommendations(response.data); }).catch(() => { if (!cancelled) setError('Unable to load recommendations.'); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [ready, profile, reloadKey]); return { recommendations, loading, error, reload }; }
export function useCitizenSavedSchemes() { const [saved, setSaved] = useState<string[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { let cancelled = false; axios.get<string[]>('/api/citizen/saved-schemes').then(response => { if (!cancelled) setSaved(response.data); }).catch(() => { if (!cancelled) setSaved([]); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []); const toggleSave = (id: string) => { if (saved.includes(id)) { setSaved(current => current.filter(item => item !== id)); axios.delete(`/api/citizen/saved-schemes/${encodeURIComponent(id)}`).catch(() => { setSaved(current => current.includes(id) ? current : [...current, id]); }); } else { setSaved(current => current.includes(id) ? current : [...current, id]); axios.post('/api/citizen/saved-schemes', { schemeId: id }).catch(() => { setSaved(current => current.filter(item => item !== id)); }); } }; const remove = (id: string) => { setSaved(current => current.filter(item => item !== id)); axios.delete(`/api/citizen/saved-schemes/${encodeURIComponent(id)}`).catch(() => { setSaved(current => current.includes(id) ? current : [...current, id]); }); }; return { saved, loading, toggleSave, remove }; }
export function CitizenProgress({ step, total, label }: { step: number; total: number; label: string }) { const shown = Math.max(1, total); const current = Math.min(step + 1, shown); const { t } = useLanguage(); return <div className="mx-auto flex max-w-3xl items-center gap-2 px-6 pt-8 md:px-0"><div className="flex-1"><div className="flex justify-between font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground"><span>{format(t('citizen.stepProgress'), { current, shown })}</span><span>{label}</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all duration-300" style={{ width: `${(current / shown) * 100}%` }} /></div></div></div>; }
export function Field({ label, value, onChange, options, hint }: { label: string; value: string; onChange: (value: string) => void; options?: string[]; hint?: string }) { const { tv } = useLanguage(); return <label className="block"><span className="text-sm font-medium">{tv(label)}</span>{hint && <span className="mt-1 block text-xs text-muted-foreground">{tv(hint)}</span>}{options ? <select value={value} onChange={event => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-border bg-card px-4 py-3.5 text-sm outline-none transition focus:border-primary">{options.map(option => <option key={option} value={option}>{tv(option)}</option>)}</select> : <input value={value} onChange={event => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-border bg-card px-4 py-3.5 text-sm outline-none transition focus:border-primary" />}</label> }
