import { useEffect, useState, type ReactNode } from 'react';
import { Link, useLocation } from 'wouter';
import {
  ArrowRight, BarChart3, Bell, BookOpen, ChevronDown, ChevronRight, ClipboardCheck, Command,
  GitBranch, Layers3, LogOut, Menu, MoreHorizontal, Network, Search, SlidersHorizontal, Table2,
  Target, X, Zap, type LucideIcon,
} from 'lucide-react';
import { Logo } from '../lib/ui';
import { useDistricts, useSchemes } from '../lib/api';
import { useLanguage } from '../lib/i18n';
import { useAuth } from '../lib/auth';
import { LanguageSwitcher } from './LanguageSwitcher';
import { ThemeToggle } from './ThemeToggle';

export const navGroups: { label: string; items: { href: string; label: string; icon: LucideIcon }[] }[] = [
  { label: 'Intelligence', items: [{ href: '/dashboard', label: 'Overview', icon: BarChart3 }, { href: '/gap-radar', label: 'Gap Radar', icon: Target }, { href: '/welfare-graph', label: 'Welfare Graph', icon: Network }, { href: '/opportunity-radar', label: 'Opportunity Radar', icon: Zap }, { href: '/maps', label: 'Maps', icon: Layers3 }] },
  { label: 'Governance', items: [{ href: '/rule-consistency', label: 'Rule Consistency', icon: GitBranch }, { href: '/simulator', label: 'What-If Simulator', icon: SlidersHorizontal }, { href: '/verification', label: 'Verification Queue', icon: ClipboardCheck }, { href: '/audit', label: 'Audit Trail', icon: Table2 }] },
];

export function ConsoleSidebar({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [location] = useLocation(); const { language } = useLanguage(); const navHindi: Record<string, string> = { Intelligence: 'इंटेलिजेंस', Governance: 'गवर्नेंस', Overview: 'ओवरव्यू', 'Gap Radar': 'गैप रडार', 'Welfare Graph': 'कल्याण ग्राफ', 'Opportunity Radar': 'अवसर रडार', Maps: 'मानचित्र', 'Rule Consistency': 'नियम संगति', 'What-If Simulator': 'क्या-अगर सिम्युलेटर', 'Verification Queue': 'सत्यापन कतार', 'Audit Trail': 'ऑडिट ट्रेल' };
  return <aside className={`fixed inset-y-0 left-0 z-50 flex w-[258px] flex-col border-r border-border bg-secondary px-5 py-6 transition-transform duration-300 md:static md:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
    <div className="flex items-center justify-between"><Link href="/dashboard" onClick={onClose}><Logo /></Link><button onClick={onClose} className="grid h-8 w-8 place-items-center rounded-full hover:bg-background md:hidden"><X size={15} /></button></div>
    <div className="mt-12 flex-1 space-y-8 overflow-y-auto">{navGroups.map(group => <div key={group.label}><div className="mb-3 px-3 font-mono text-[9px] uppercase tracking-[0.2em] text-muted-foreground">{language === 'hi' ? navHindi[group.label] : group.label}</div><nav className="space-y-1">{group.items.map(item => { const active = location === item.href; const Icon = item.icon; return <Link href={item.href} key={item.href} onClick={onClose} className={`group flex items-center gap-3 rounded-lg border-l-2 px-3 py-2.5 text-sm transition ${active ? 'border-brand-terracotta bg-background font-medium text-foreground' : 'border-transparent text-muted-foreground hover:bg-background/70 hover:text-foreground'}`}><Icon size={16} strokeWidth={active ? 2 : 1.7} /><span>{language === 'hi' ? navHindi[item.label] : item.label}</span>{item.label === 'Verification Queue' && <span className="ml-auto rounded-full bg-terracotta px-1.5 py-0.5 font-mono text-[9px] text-terracotta-fg">4</span>}</Link> })}</nav></div>)}</div>
    <div className="border-t border-border pt-5"><div className="mb-4 flex items-center gap-2 px-2"><span className="h-2 w-2 rounded-full bg-primary shadow-[0_0_0_4px_rgba(85,122,99,.13)]" /><div><div className="font-mono text-[9px] uppercase tracking-[0.16em] text-primary">System status</div><div className="text-xs text-muted-foreground">All signals operational</div></div></div><div className="flex items-center gap-3 rounded-lg bg-background/65 p-3"><div className="grid h-8 w-8 place-items-center rounded-full bg-foreground font-display text-sm text-background">AD</div><div className="min-w-0"><div className="truncate text-xs font-medium">District Administrator</div><div className="font-mono text-[9px] uppercase tracking-[0.1em] text-muted-foreground">India · pilot</div></div><MoreHorizontal size={15} className="ml-auto text-muted-foreground" /></div><AdminLogout /></div>
  </aside>;
}

export function TopBar({ onMenu, onCommand }: { onMenu: () => void; onCommand: () => void }) {
  return <header className="flex h-[76px] items-center justify-between border-b border-border bg-background/90 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button onClick={onMenu} className="grid h-9 w-9 place-items-center rounded-full border border-border bg-secondary md:hidden"><Menu size={16} /></button><div className="hidden items-center gap-2 font-mono text-[10px] uppercase tracking-[0.16em] text-brand-indigo sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-brand-indigo" /> India <ChevronRight size={12} className="text-muted-foreground" /> All schemes</div></div><div className="flex items-center gap-2 md:gap-4"><Link href="/citizen" className="hidden rounded-full border border-border px-3 py-2 font-mono text-[10px] uppercase tracking-[0.12em] text-primary transition hover:bg-sage sm:block">Citizen assistance</Link><LanguageSwitcher /><ThemeToggle /><button onClick={onCommand} className="hidden items-center gap-3 rounded-full border border-border bg-secondary/70 px-3 py-2 font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground transition hover:border-primary hover:text-foreground sm:flex"><Search size={14} /> Search <kbd className="rounded border border-border px-1.5 py-0.5 text-[9px]">⌘K</kbd></button><div className="hidden font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground lg:block">Updated 12 min ago</div><button className="relative grid h-9 w-9 place-items-center rounded-full border border-border bg-secondary/70"><Bell size={16} /><span className="absolute right-1 top-1 h-1.5 w-1.5 rounded-full bg-brand-terracotta" /></button><div className="hidden items-center gap-2 border-l border-border pl-4 sm:flex"><div className="grid h-8 w-8 place-items-center rounded-full bg-foreground font-display text-xs text-background">AD</div><span className="text-xs font-medium">Administrator</span><ChevronDown size={13} className="text-muted-foreground" /></div></div></header>;
}

export function CommandPalette({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [, navigate] = useLocation();
  const [query, setQuery] = useState('');
  const { schemes } = useSchemes();
  const { districts } = useDistricts();
  const commands = [{ label: 'Go to Gap Radar', href: '/gap-radar', icon: Target }, { label: 'Go to Simulator', href: '/simulator', icon: SlidersHorizontal }, { label: 'Open Verification Queue', href: '/verification', icon: ClipboardCheck }, { label: 'Search District', href: '/maps', icon: Search }, { label: 'View Audit Trail', href: '/audit', icon: Table2 }];
  const term = query.trim().toLowerCase();
  const results = term ? [...schemes.filter(item => `${item.name} ${item.category}`.toLowerCase().includes(term)).map(item => ({ label: item.name, meta: item.category, href: `/citizen/scheme/${item.id}`, icon: BookOpen })), ...districts.filter(item => `${item.name} ${item.state} ${item.locality}`.toLowerCase().includes(term)).map(item => ({ label: item.name, meta: `${item.state} · ${item.scheme}`, href: '/gap-radar', icon: Target }))] : [];
  if (!open) return null;
  return <div className="fixed inset-0 z-[70] grid place-items-start bg-[#18231f]/30 px-4 pt-[15vh] backdrop-blur-sm" onClick={onClose}><div className="w-full max-w-lg overflow-hidden rounded-2xl bg-card shadow-2xl" onClick={e => e.stopPropagation()}><div className="flex items-center gap-3 border-b border-border px-5 py-4"><Command size={17} className="text-primary" /><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="What would you like to inspect?" className="flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground" /><kbd className="font-mono text-[10px] text-muted-foreground">ESC</kbd></div><div className="max-h-[360px] overflow-y-auto p-2">{(term ? results : commands).length ? (term ? results : commands).map(item => <button key={item.href + item.label} onClick={() => { navigate(item.href); onClose(); setQuery(''); }} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition hover:bg-secondary"><span className="grid h-8 w-8 place-items-center rounded-lg bg-sage text-primary"><item.icon size={15} /></span><span className="flex-1"><span className="block">{item.label}</span>{'meta' in item && typeof item.meta === 'string' && <span className="mt-0.5 block text-xs text-muted-foreground">{item.meta}</span>}</span><ArrowRight size={14} className="text-muted-foreground" /></button>) : <div className="px-4 py-8 text-center text-sm text-muted-foreground">No local records match “{query}”.</div>}</div><div className="flex items-center justify-between border-t border-border px-5 py-3 font-mono text-[9px] uppercase tracking-[0.14em] text-muted-foreground"><span>{term ? 'Local data search' : 'Navigate intelligence'}</span><span>ESC</span></div></div></div>;
}
export function ConsoleLayout({ children }: { children: ReactNode }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [commandOpen, setCommandOpen] = useState(false);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommandOpen(true); } if (event.key === 'Escape') setCommandOpen(false); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);
  return <div className="flex min-h-screen bg-background text-foreground"><ConsoleSidebar open={sidebarOpen} onClose={() => setSidebarOpen(false)} />{sidebarOpen && <div className="fixed inset-0 z-40 bg-[#18231f]/25 md:hidden" onClick={() => setSidebarOpen(false)} />}<div className="flex min-w-0 flex-1 flex-col"><TopBar onMenu={() => setSidebarOpen(true)} onCommand={() => setCommandOpen(true)} /><main className="flex-1 overflow-y-auto"><div className="mx-auto max-w-[1500px] px-5 py-8 md:px-8 md:py-10">{children}</div></main></div><CommandPalette open={commandOpen} onClose={() => setCommandOpen(false)} /></div>;
}
export function AdminLogout() { const [, navigate] = useLocation(); const { t } = useLanguage(); const { logout } = useAuth(); return <button onClick={() => { logout(); navigate('/admin-login'); }} className="mt-3 flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground transition hover:bg-background hover:text-terracotta-fg"><LogOut size={13} /> {t('nav.logout')}</button>; }
export function RedirectToLogin() { const [, navigate] = useLocation(); useEffect(() => { navigate('/admin-login'); }, [navigate]); return <div className="grid min-h-screen place-items-center bg-background text-sm text-muted-foreground">Opening administrator sign in…</div>; }
